# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'recipes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for recipes
  pod 'SDWebImage', '~> 4.0'

  target 'recipesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recipesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
